"""First migration with Stock and FinancialReport

Revision ID: 9c6d494e2430
Revises: 
Create Date: 2025-09-26 23:42:38.722930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6d494e2430'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('curr_equity_ratio', sa.Float(), nullable=True),
    sa.Column('curr_net_debt_to_ebitda', sa.Float(), nullable=True),
    sa.Column('mrq_inv_to_rev', sa.Float(), nullable=True),
    sa.Column('avg_inv_to_rev', sa.Float(), nullable=True),
    sa.Column('mrq_yoy_rev_growth', sa.Float(), nullable=True),
    sa.Column('avg_rev_growth', sa.Float(), nullable=True),
    sa.Column('mrq_gp_margin', sa.Float(), nullable=True),
    sa.Column('avg_gp_margin', sa.Float(), nullable=True),
    sa.Column('mrq_fcf_margin', sa.Float(), nullable=True),
    sa.Column('avg_fcf_margin', sa.Float(), nullable=True),
    sa.Column('curr_div_rate_rev', sa.Float(), nullable=True),
    sa.Column('curr_end_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.String(length=50), nullable=True),
    sa.Column('curr_ev_to_rev', sa.Float(), nullable=True),
    sa.Column('avg_ev_to_rev', sa.Float(), nullable=True),
    sa.Column('curr_fcf_to_rev', sa.Float(), nullable=True),
    sa.Column('avg_fcf_to_rev', sa.Float(), nullable=True),
    sa.Column('curr_fwd_div', sa.Float(), nullable=True),
    sa.Column('avg_fwd_div', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_ticker'), ['ticker'], unique=True)

    op.create_table('financial_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.Enum('QUARTERLY', 'ANNUAL', name='reporttype'), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_equity', sa.BigInteger(), nullable=True),
    sa.Column('total_liability', sa.BigInteger(), nullable=True),
    sa.Column('cash_and_equivalents', sa.BigInteger(), nullable=True),
    sa.Column('total_debt', sa.BigInteger(), nullable=True),
    sa.Column('inventory', sa.BigInteger(), nullable=True),
    sa.Column('revenue', sa.BigInteger(), nullable=True),
    sa.Column('gross_profit', sa.BigInteger(), nullable=True),
    sa.Column('ebitda', sa.BigInteger(), nullable=True),
    sa.Column('free_cash_flow', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('financial_report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financial_report_stock_id'), ['stock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financial_report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financial_report_stock_id'))

    op.drop_table('financial_report')
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_ticker'))

    op.drop_table('stock')
    # ### end Alembic commands ###
